/**
 * Career Services catalog.
 *
 * Service definitions live in code rather than a table: they carry behaviour
 * (required inputs, Talent Passport prefill, repeat rules, scheduling) that the
 * UI and the transition rules read directly. Requests are what gets persisted.
 * Adding services 07-26 later is a data-only change to this file.
 */
import type { CareerService, CareerServiceCategory } from '@/types/domain'

export const CAREER_SERVICE_CATEGORIES: {
  key: CareerServiceCategory
  label: string
  labelAr: string
  description: string
  descriptionAr: string
}[] = [
  {
    key: 'cv_branding',
    label: 'CV & Branding',
    labelAr: 'السيرة الذاتية والهوية المهنية',
    description: 'Make your CV and professional profile represent you accurately.',
    descriptionAr: 'اجعل سيرتك الذاتية وملفك المهني يعكسان خبرتك بدقة.',
  },
  {
    key: 'applications',
    label: 'Applications',
    labelAr: 'طلبات التوظيف',
    description: 'Prepare stronger applications for the roles you want.',
    descriptionAr: 'جهّز طلبات توظيف أقوى للوظائف التي تستهدفها.',
  },
  {
    key: 'interview_prep',
    label: 'Interview Preparation',
    labelAr: 'التحضير للمقابلات',
    description: 'Practise and prepare before you meet an employer.',
    descriptionAr: 'تدرّب وجهّز نفسك قبل مقابلة صاحب العمل.',
  },
]

export const CAREER_SERVICES: CareerService[] = [
  {
    id: 'cv-readiness-check',
    code: '07',
    name: 'CV Readiness Check',
    nameAr: 'فحص جاهزية السيرة الذاتية',
    category: 'cv_branding',
    pricingType: 'free',
    description:
      'A quick structured check of how ready your CV and Talent Passport are, with the specific areas to fix next.',
    descriptionAr:
      'فحص سريع لمدى جاهزية سيرتك الذاتية وجواز المواهب، مع تحديد النقاط التي تحتاج تحسيناً.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'assessment',
    allowsRepeatRequests: true,
    selfService: true,
    inputFields: [
      {
        key: 'targetRole',
        label: 'Target role',
        labelAr: 'الوظيفة المستهدفة',
        type: 'text',
        required: false,
        placeholder: 'e.g. Data Analyst',
        prefillFrom: 'headline',
      },
      {
        key: 'cvTailored',
        label: 'Do you tailor your CV for each application?',
        labelAr: 'هل تعدّل سيرتك الذاتية لكل وظيفة تتقدم لها؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'achievementsQuantified',
        label: 'Does your CV describe results with numbers?',
        labelAr: 'هل تصف إنجازاتك بأرقام في سيرتك الذاتية؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'contactDetailsCurrent',
        label: 'Are your contact details current on the CV?',
        labelAr: 'هل بيانات التواصل في سيرتك الذاتية محدّثة؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'onePageFormat',
        label: 'Is your CV a clean, consistent 1-2 page layout?',
        labelAr: 'هل سيرتك الذاتية بتنسيق واضح ومتناسق من صفحة إلى صفحتين؟',
        type: 'boolean',
        required: true,
      },
    ],
  },
  {
    id: 'professional-cv-writing',
    code: '08',
    name: 'Professional CV Writing',
    nameAr: 'كتابة السيرة الذاتية الاحترافية',
    category: 'cv_branding',
    pricingType: 'paid',
    description:
      'Our career team writes a professional CV for you using your Talent Passport, and returns the finished document.',
    descriptionAr:
      'يكتب فريق المسار المهني سيرة ذاتية احترافية لك باستخدام جواز المواهب، ويسلّمك الملف النهائي.',
    active: true,
    requiresJobDescription: false,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'document',
    allowsRepeatRequests: false,
    selfService: false,
    inputFields: [
      {
        key: 'targetRole',
        label: 'Target role or career direction',
        labelAr: 'الوظيفة أو المسار المهني المستهدف',
        type: 'text',
        required: true,
        placeholder: 'e.g. NGO Programme Officer',
        prefillFrom: 'headline',
      },
      {
        key: 'targetSector',
        label: 'Target sector',
        labelAr: 'القطاع المستهدف',
        type: 'select',
        required: false,
        options: [
          { value: 'private', label: 'Private sector', labelAr: 'القطاع الخاص' },
          { value: 'ngo', label: 'NGO / INGO', labelAr: 'المنظمات غير الحكومية' },
          { value: 'public', label: 'Public sector', labelAr: 'القطاع العام' },
          { value: 'academia', label: 'Academia', labelAr: 'الأكاديمي' },
        ],
      },
      {
        key: 'highlights',
        label: 'Anything you want emphasised?',
        labelAr: 'هل هناك ما ترغب بإبرازه؟',
        type: 'textarea',
        required: false,
        helpText: 'Your education, experience and skills are taken from your Talent Passport.',
        helpTextAr: 'يتم أخذ تعليمك وخبراتك ومهاراتك من جواز المواهب تلقائياً.',
      },
    ],
  },
  {
    id: 'linkedin-profile-optimization',
    code: '12',
    name: 'LinkedIn Profile Optimization',
    nameAr: 'تحسين الملف الشخصي على لينكدإن',
    category: 'cv_branding',
    pricingType: 'paid',
    description:
      'A reviewed LinkedIn profile with concrete rewrites for your headline, About section and experience.',
    descriptionAr:
      'مراجعة ملفك على لينكدإن مع صياغات مقترحة للعنوان والنبذة والخبرات.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: false,
    selfService: false,
    inputFields: [
      {
        key: 'linkedinUrl',
        label: 'LinkedIn profile URL',
        labelAr: 'رابط ملفك على لينكدإن',
        type: 'url',
        required: true,
        placeholder: 'https://linkedin.com/in/your-profile',
        prefillFrom: 'linkedinUrl',
      },
      {
        key: 'targetRole',
        label: 'Role you want recruiters to find you for',
        labelAr: 'الوظيفة التي تريد أن يجدك بها مسؤولو التوظيف',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
    ],
  },
  {
    id: 'interview-preparation-session',
    code: '20',
    name: 'Interview Preparation Session',
    nameAr: 'جلسة التحضير للمقابلة',
    category: 'interview_prep',
    pricingType: 'paid',
    description:
      'A one-to-one session with the career team to prepare for a specific interview, scheduled at a time that suits you.',
    descriptionAr:
      'جلسة فردية مع فريق المسار المهني للتحضير لمقابلة محددة، في موعد يناسبك.',
    active: true,
    requiresJobDescription: true,
    requiresCV: false,
    requiresScheduling: true,
    resultType: 'session',
    allowsRepeatRequests: true,
    selfService: false,
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are interviewing for',
        labelAr: 'الوظيفة التي ستُجري المقابلة لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'interviewDate',
        label: 'When is the interview?',
        labelAr: 'متى موعد المقابلة؟',
        type: 'text',
        required: false,
        placeholder: 'YYYY-MM-DD, or "not scheduled yet"',
      },
      {
        key: 'availability',
        label: 'When are you available for the session?',
        labelAr: 'ما الأوقات المناسبة لك للجلسة؟',
        type: 'textarea',
        required: true,
        helpText: 'Give a few options. The career team confirms one of them.',
        helpTextAr: 'اذكر عدة خيارات، وسيؤكد الفريق أحدها.',
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: true,
        helpText: 'Paste the posting so the session is specific to it.',
        helpTextAr: 'الصق الإعلان الوظيفي لتكون الجلسة مخصصة له.',
      },
    ],
  },
  {
    id: 'ats-friendly-cv-optimization',
    code: '09',
    name: 'ATS-Friendly CV Optimization',
    nameAr: 'تحسين السيرة الذاتية لأنظمة التتبع',
    category: 'cv_branding',
    pricingType: 'paid',
    description:
      'Your existing CV rewritten to pass applicant tracking systems, with the right structure, headings and keywords.',
    descriptionAr:
      'إعادة صياغة سيرتك الذاتية لتجتاز أنظمة تتبع المتقدمين، ببنية وعناوين وكلمات مفتاحية مناسبة.',
    active: true,
    requiresJobDescription: false,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'document',
    allowsRepeatRequests: false,
    selfService: false,
    followUpServiceCode: '10',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Target role',
        labelAr: 'الوظيفة المستهدفة',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
        helpText: 'Your uploaded CV and Talent Passport are used as the source material.',
        helpTextAr: 'يتم استخدام سيرتك الذاتية المرفوعة وجواز المواهب كمصدر للمعلومات.',
      },
      {
        key: 'targetSector',
        label: 'Target sector',
        labelAr: 'القطاع المستهدف',
        type: 'select',
        required: false,
        options: [
          { value: 'private', label: 'Private sector', labelAr: 'القطاع الخاص' },
          { value: 'ngo', label: 'NGO / INGO', labelAr: 'المنظمات غير الحكومية' },
          { value: 'public', label: 'Public sector', labelAr: 'القطاع العام' },
          { value: 'academia', label: 'Academia', labelAr: 'الأكاديمي' },
        ],
      },
    ],
  },
  {
    id: 'job-specific-cv-customization',
    code: '10',
    name: 'Job-Specific CV Customization',
    nameAr: 'تخصيص السيرة الذاتية لوظيفة محددة',
    category: 'cv_branding',
    pricingType: 'paid',
    description:
      'Your CV tailored to one specific vacancy, mirroring the language and priorities of that posting.',
    descriptionAr:
      'تخصيص سيرتك الذاتية لوظيفة محددة بما يتوافق مع لغة الإعلان وأولوياته.',
    active: true,
    requiresJobDescription: true,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'document',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '16',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Job title',
        labelAr: 'المسمى الوظيفي',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: true,
        helpText: 'Paste the full vacancy text so the CV can be aligned to it.',
        helpTextAr: 'الصق نص الإعلان الوظيفي كاملاً ليتم مواءمة السيرة الذاتية معه.',
      },
      {
        key: 'deadline',
        label: 'Application deadline',
        labelAr: 'آخر موعد للتقديم',
        type: 'text',
        required: false,
        placeholder: 'YYYY-MM-DD',
      },
    ],
  },
  {
    id: 'ngo-ingo-cv-preparation',
    code: '11',
    name: 'NGO & INGO CV Preparation',
    nameAr: 'إعداد السيرة الذاتية للمنظمات غير الحكومية',
    category: 'cv_branding',
    pricingType: 'paid',
    description:
      'A CV built to the conventions humanitarian and development organizations expect, including competency framing.',
    descriptionAr:
      'سيرة ذاتية مُعدّة وفق معايير المنظمات الإنسانية والتنموية، بما في ذلك صياغة الكفاءات.',
    active: true,
    requiresJobDescription: false,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'document',
    allowsRepeatRequests: false,
    selfService: false,
    followUpServiceCode: '18',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Target role',
        labelAr: 'الوظيفة المستهدفة',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'sectorFocus',
        label: 'Sector focus',
        labelAr: 'مجال التركيز',
        type: 'select',
        required: true,
        options: [
          { value: 'humanitarian', label: 'Humanitarian response', labelAr: 'الاستجابة الإنسانية' },
          { value: 'development', label: 'Development', labelAr: 'التنمية' },
          { value: 'health', label: 'Health', labelAr: 'الصحة' },
          { value: 'education', label: 'Education', labelAr: 'التعليم' },
          { value: 'protection', label: 'Protection', labelAr: 'الحماية' },
          { value: 'operations', label: 'Operations & logistics', labelAr: 'العمليات واللوجستيات' },
        ],
      },
      {
        key: 'targetOrganizations',
        label: 'Organizations you are targeting',
        labelAr: 'المنظمات التي تستهدفها',
        type: 'textarea',
        required: false,
      },
    ],
  },
  {
    id: 'job-application-readiness-check',
    code: '13',
    name: 'Job Application Readiness Check',
    nameAr: 'فحص جاهزية طلب التوظيف',
    category: 'applications',
    pricingType: 'free',
    description:
      'A structured check of whether you are ready to apply for a specific role, and what to fix first.',
    descriptionAr:
      'فحص منظّم لمدى جاهزيتك للتقدم لوظيفة محددة، مع تحديد ما يجب معالجته أولاً.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'assessment',
    allowsRepeatRequests: true,
    selfService: true,
    followUpServiceCode: '10',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are applying for',
        labelAr: 'الوظيفة التي تتقدم لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'cvTailoredForTarget',
        label: 'Is your CV tailored to this specific role?',
        labelAr: 'هل سيرتك الذاتية مخصصة لهذه الوظيفة تحديداً؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'coverLetterReady',
        label: 'Do you have a cover letter ready for it?',
        labelAr: 'هل لديك رسالة تغطية جاهزة لها؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'referencesReady',
        label: 'Are your references ready to be contacted?',
        labelAr: 'هل مراجعك المهنية جاهزة للتواصل معها؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'deadlinesTracked',
        label: 'Are you tracking the application deadline?',
        labelAr: 'هل تتابع آخر موعد للتقديم؟',
        type: 'boolean',
        required: true,
      },
    ],
  },
  {
    id: 'job-description-analysis',
    code: '14',
    name: 'Job Description Analysis',
    nameAr: 'تحليل الوصف الوظيفي',
    category: 'applications',
    pricingType: 'free',
    pricingNote: 'In-depth analysis available as a premium service.',
    pricingNoteAr: 'يتوفر تحليل معمّق كخدمة مميزة.',
    description:
      'The career team breaks a vacancy down into required qualifications, experience, key skills, responsibilities and keywords.',
    descriptionAr:
      'يحلل فريق المسار المهني الإعلان الوظيفي إلى المؤهلات والخبرات والمهارات والمسؤوليات والكلمات المفتاحية المطلوبة.',
    active: true,
    requiresJobDescription: true,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '15',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Job title',
        labelAr: 'المسمى الوظيفي',
        type: 'text',
        required: true,
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'jobDescription',
        label: 'Vacancy text',
        labelAr: 'نص الإعلان الوظيفي',
        type: 'textarea',
        required: true,
        helpText: 'Paste the posting, or the link plus any text you have.',
        helpTextAr: 'الصق الإعلان أو الرابط مع أي نص متوفر لديك.',
      },
    ],
  },
  {
    id: 'cv-to-job-matching',
    code: '15',
    name: 'CV-to-Job Matching',
    nameAr: 'مطابقة السيرة الذاتية بالوظيفة',
    category: 'applications',
    pricingType: 'premium',
    description:
      'A career specialist compares your CV against a vacancy and reports strong matches, missing requirements and skills gaps.',
    descriptionAr:
      'يقارن مختص المسار المهني سيرتك الذاتية بالإعلان الوظيفي ويحدد نقاط التطابق والمتطلبات الناقصة والفجوات.',
    active: true,
    requiresJobDescription: true,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '10',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Job title',
        labelAr: 'المسمى الوظيفي',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'jobDescription',
        label: 'Vacancy text',
        labelAr: 'نص الإعلان الوظيفي',
        type: 'textarea',
        required: true,
        helpText:
          'Reviewed by a career specialist against your CV and Talent Passport. This is a human review, not an automated score.',
        helpTextAr:
          'تتم المراجعة من قبل مختص مقارنةً بسيرتك الذاتية وجواز المواهب. هذه مراجعة بشرية وليست تقييماً آلياً.',
      },
    ],
  },
  {
    id: 'professional-cover-letter',
    code: '16',
    name: 'Professional Cover Letter',
    nameAr: 'رسالة تغطية احترافية',
    category: 'applications',
    pricingType: 'paid',
    description:
      'A cover letter written for one specific vacancy, drawing on your Talent Passport and CV.',
    descriptionAr:
      'رسالة تغطية مكتوبة لوظيفة محددة، بالاعتماد على جواز المواهب وسيرتك الذاتية.',
    active: true,
    requiresJobDescription: true,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'document',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '17',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Job title',
        labelAr: 'المسمى الوظيفي',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: true,
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: true,
      },
      {
        key: 'motivation',
        label: 'Why do you want this role?',
        labelAr: 'لماذا ترغب بهذه الوظيفة؟',
        type: 'textarea',
        required: false,
        helpText: 'A few lines in your own words help the letter sound like you.',
        helpTextAr: 'بضعة أسطر بكلماتك تساعد على أن تعكس الرسالة شخصيتك.',
      },
    ],
  },
  {
    id: 'job-application-review',
    code: '17',
    name: 'Job Application Review',
    nameAr: 'مراجعة طلب التوظيف',
    category: 'applications',
    pricingType: 'paid',
    description:
      'A specialist reviews your complete application before you send it and tells you what to strengthen.',
    descriptionAr:
      'يراجع المختص طلبك الكامل قبل إرساله ويحدد ما يجب تقويته.',
    active: true,
    requiresJobDescription: true,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    inputFields: [
      {
        key: 'targetRole',
        label: 'Job title',
        labelAr: 'المسمى الوظيفي',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: true,
      },
      {
        key: 'applicationMaterials',
        label: 'What are you submitting?',
        labelAr: 'ما الذي ستقوم بإرساله؟',
        type: 'textarea',
        required: true,
        helpText: 'List the documents, and paste any text you want reviewed.',
        helpTextAr: 'اذكر المستندات، والصق أي نص ترغب بمراجعته.',
      },
      {
        key: 'concerns',
        label: 'Anything you are unsure about?',
        labelAr: 'هل هناك ما لست متأكداً منه؟',
        type: 'textarea',
        required: false,
      },
    ],
  },
  {
    id: 'ngo-ingo-application-preparation',
    code: '18',
    name: 'NGO & INGO Application Preparation',
    nameAr: 'إعداد طلبات التوظيف للمنظمات غير الحكومية',
    category: 'applications',
    pricingType: 'premium',
    description:
      'Full preparation for a humanitarian or development application, including competency-based written answers.',
    descriptionAr:
      'إعداد كامل لطلب توظيف في المجال الإنساني أو التنموي، بما في ذلك الإجابات المبنية على الكفاءات.',
    active: true,
    requiresJobDescription: true,
    requiresCV: true,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '25',
    inputFields: [
      {
        key: 'employer',
        label: 'Organization',
        labelAr: 'المنظمة',
        type: 'text',
        required: true,
      },
      {
        key: 'sectorFocus',
        label: 'Sector focus',
        labelAr: 'مجال التركيز',
        type: 'select',
        required: true,
        options: [
          { value: 'humanitarian', label: 'Humanitarian response', labelAr: 'الاستجابة الإنسانية' },
          { value: 'development', label: 'Development', labelAr: 'التنمية' },
          { value: 'health', label: 'Health', labelAr: 'الصحة' },
          { value: 'education', label: 'Education', labelAr: 'التعليم' },
          { value: 'protection', label: 'Protection', labelAr: 'الحماية' },
          { value: 'operations', label: 'Operations & logistics', labelAr: 'العمليات واللوجستيات' },
        ],
      },
      {
        key: 'jobDescription',
        label: 'Vacancy text',
        labelAr: 'نص الإعلان الوظيفي',
        type: 'textarea',
        required: true,
      },
      {
        key: 'applicationQuestions',
        label: 'Application questions to prepare',
        labelAr: 'أسئلة الطلب المطلوب تجهيزها',
        type: 'textarea',
        required: false,
        helpText: 'Paste any motivation or competency questions the form asks.',
        helpTextAr: 'الصق أسئلة الدافعية أو الكفاءات الواردة في نموذج التقديم.',
      },
    ],
  },
  {
    id: 'interview-readiness-assessment',
    code: '19',
    name: 'Interview Readiness Assessment',
    nameAr: 'تقييم الجاهزية للمقابلة',
    category: 'interview_prep',
    pricingType: 'free',
    description:
      'A short structured check of how prepared you are for an interview, and exactly what to work on next.',
    descriptionAr:
      'فحص منظّم قصير لمدى استعدادك للمقابلة، مع تحديد ما يجب العمل عليه.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'assessment',
    allowsRepeatRequests: true,
    selfService: true,
    followUpServiceCode: '20',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are interviewing for',
        labelAr: 'الوظيفة التي ستُجري المقابلة لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'introductionPrepared',
        label: 'Can you deliver a clear two-minute professional introduction?',
        labelAr: 'هل يمكنك تقديم تعريف مهني واضح خلال دقيقتين؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'experienceExamplesPrepared',
        label: 'Have you prepared examples from your experience?',
        labelAr: 'هل جهّزت أمثلة من خبرتك العملية؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'achievementExamplesPrepared',
        label: 'Have you prepared specific achievement examples?',
        labelAr: 'هل جهّزت أمثلة محددة على إنجازاتك؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'employerResearchDone',
        label: 'Have you researched the employer?',
        labelAr: 'هل بحثت عن جهة العمل؟',
        type: 'boolean',
        required: true,
      },
      {
        key: 'questionsPrepared',
        label: 'Have you prepared questions to ask them?',
        labelAr: 'هل جهّزت أسئلة لطرحها عليهم؟',
        type: 'boolean',
        required: true,
      },
    ],
  },
  {
    id: 'professional-mock-interview',
    code: '21',
    name: 'Professional Mock Interview',
    nameAr: 'مقابلة تجريبية احترافية',
    category: 'interview_prep',
    pricingType: 'paid',
    description:
      'A full practice interview with a career specialist at a scheduled time, followed by direct feedback.',
    descriptionAr:
      'مقابلة تدريبية كاملة مع مختص في موعد محدد، تليها تغذية راجعة مباشرة.',
    active: true,
    requiresJobDescription: true,
    requiresCV: false,
    requiresScheduling: true,
    resultType: 'session',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '26',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are interviewing for',
        labelAr: 'الوظيفة التي ستُجري المقابلة لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'employer',
        label: 'Employer',
        labelAr: 'جهة العمل',
        type: 'text',
        required: false,
      },
      {
        key: 'interviewFormat',
        label: 'Interview format',
        labelAr: 'نمط المقابلة',
        type: 'select',
        required: true,
        options: [
          { value: 'one_to_one', label: 'One-to-one', labelAr: 'فردية' },
          { value: 'panel', label: 'Panel', labelAr: 'لجنة' },
          { value: 'competency', label: 'Competency-based', labelAr: 'مبنية على الكفاءات' },
          { value: 'technical', label: 'Technical', labelAr: 'تقنية' },
        ],
      },
      {
        key: 'availability',
        label: 'When are you available?',
        labelAr: 'ما الأوقات المناسبة لك؟',
        type: 'textarea',
        required: true,
        helpText: 'Give a few options. The career team confirms one of them.',
        helpTextAr: 'اذكر عدة خيارات، وسيؤكد الفريق أحدها.',
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: true,
      },
    ],
  },
  {
    id: 'ai-interview-simulator',
    code: '22',
    name: 'AI Interview Simulator',
    nameAr: 'محاكي المقابلات بالذكاء الاصطناعي',
    category: 'interview_prep',
    pricingType: 'premium',
    description:
      'Practise interviews on demand with an AI interviewer. Not available yet.',
    descriptionAr:
      'تدرّب على المقابلات في أي وقت مع محاور بالذكاء الاصطناعي. غير متاح حالياً.',
    active: false,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'assessment',
    allowsRepeatRequests: false,
    selfService: false,
    inputFields: [],
  },
  {
    id: 'competency-based-interview-preparation',
    code: '23',
    name: 'Competency-Based Interview Preparation',
    nameAr: 'التحضير للمقابلات المبنية على الكفاءات',
    category: 'interview_prep',
    pricingType: 'paid',
    description:
      'Prepare structured competency answers using the STAR method, matched to the competencies the employer asks for.',
    descriptionAr:
      'تجهيز إجابات منظمة للكفاءات بأسلوب STAR، بما يتوافق مع الكفاءات المطلوبة من جهة العمل.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '21',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are interviewing for',
        labelAr: 'الوظيفة التي ستُجري المقابلة لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'keyCompetencies',
        label: 'Competencies to prepare',
        labelAr: 'الكفاءات المطلوب تجهيزها',
        type: 'textarea',
        required: true,
        helpText: 'For example: teamwork, problem solving, working under pressure.',
        helpTextAr: 'مثال: العمل الجماعي، حل المشكلات، العمل تحت الضغط.',
      },
      {
        key: 'jobDescription',
        label: 'Job description',
        labelAr: 'الوصف الوظيفي',
        type: 'textarea',
        required: false,
      },
    ],
  },
  {
    id: 'english-interview-preparation',
    code: '24',
    name: 'English Interview Preparation',
    nameAr: 'التحضير للمقابلة باللغة الإنجليزية',
    category: 'interview_prep',
    pricingType: 'paid',
    description:
      'Prepare to interview confidently in English, with the vocabulary and phrasing your role calls for.',
    descriptionAr:
      'استعد لإجراء المقابلة بالإنجليزية بثقة، بالمفردات والصياغات التي تتطلبها وظيفتك.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '21',
    inputFields: [
      {
        key: 'targetRole',
        label: 'Role you are interviewing for',
        labelAr: 'الوظيفة التي ستُجري المقابلة لها',
        type: 'text',
        required: true,
        prefillFrom: 'headline',
      },
      {
        key: 'englishLevel',
        label: 'Your current English level',
        labelAr: 'مستواك الحالي في الإنجليزية',
        type: 'select',
        required: true,
        options: [
          { value: 'beginner', label: 'Beginner', labelAr: 'مبتدئ' },
          { value: 'intermediate', label: 'Intermediate', labelAr: 'متوسط' },
          { value: 'advanced', label: 'Advanced', labelAr: 'متقدم' },
        ],
      },
      {
        key: 'focusAreas',
        label: 'What worries you most?',
        labelAr: 'ما الذي يقلقك أكثر؟',
        type: 'textarea',
        required: false,
        helpText: 'For example: introducing yourself, technical vocabulary, speaking pace.',
        helpTextAr: 'مثال: التعريف بنفسك، المصطلحات التقنية، سرعة الحديث.',
      },
    ],
  },
  {
    id: 'ngo-ingo-interview-preparation',
    code: '25',
    name: 'NGO & INGO Interview Preparation',
    nameAr: 'التحضير لمقابلات المنظمات غير الحكومية',
    category: 'interview_prep',
    pricingType: 'premium',
    description:
      'Preparation for humanitarian and development interviews, including sector competencies and safeguarding questions.',
    descriptionAr:
      'تحضير لمقابلات المجال الإنساني والتنموي، بما يشمل كفاءات القطاع وأسئلة الحماية.',
    active: true,
    requiresJobDescription: true,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'recommendations',
    allowsRepeatRequests: true,
    selfService: false,
    followUpServiceCode: '21',
    inputFields: [
      {
        key: 'employer',
        label: 'Organization',
        labelAr: 'المنظمة',
        type: 'text',
        required: true,
      },
      {
        key: 'sectorFocus',
        label: 'Sector focus',
        labelAr: 'مجال التركيز',
        type: 'select',
        required: true,
        options: [
          { value: 'humanitarian', label: 'Humanitarian response', labelAr: 'الاستجابة الإنسانية' },
          { value: 'development', label: 'Development', labelAr: 'التنمية' },
          { value: 'health', label: 'Health', labelAr: 'الصحة' },
          { value: 'education', label: 'Education', labelAr: 'التعليم' },
          { value: 'protection', label: 'Protection', labelAr: 'الحماية' },
          { value: 'operations', label: 'Operations & logistics', labelAr: 'العمليات واللوجستيات' },
        ],
      },
      {
        key: 'jobDescription',
        label: 'Vacancy text',
        labelAr: 'نص الإعلان الوظيفي',
        type: 'textarea',
        required: true,
      },
    ],
  },
  {
    id: 'interview-performance-report',
    code: '26',
    name: 'Interview Performance Report',
    nameAr: 'تقرير أداء المقابلة',
    category: 'interview_prep',
    pricingType: 'paid',
    description:
      'A written performance report on a mock interview you have completed, with scored strengths and gaps.',
    descriptionAr:
      'تقرير مكتوب عن أدائك في مقابلة تجريبية أنجزتها، مع نقاط القوة والفجوات.',
    active: true,
    requiresJobDescription: false,
    requiresCV: false,
    requiresScheduling: false,
    resultType: 'assessment',
    allowsRepeatRequests: true,
    selfService: false,
    prerequisiteServiceCode: '21',
    inputFields: [
      {
        key: 'mockInterviewRequestId',
        label: 'Which mock interview?',
        labelAr: 'أي مقابلة تجريبية؟',
        type: 'reference',
        required: true,
        referenceServiceCode: '21',
        helpText: 'Only mock interviews you have completed are listed.',
        helpTextAr: 'تظهر فقط المقابلات التجريبية التي أنجزتها.',
      },
      {
        key: 'focusAreas',
        label: 'Anything you want the report to focus on?',
        labelAr: 'هل هناك ما تريد أن يركز عليه التقرير؟',
        type: 'textarea',
        required: false,
      },
    ],
  },
]

CAREER_SERVICES.sort((a, b) => a.code.localeCompare(b.code))

export const ACTIVE_CAREER_SERVICES = CAREER_SERVICES.filter((service) => service.active)

/** Includes inactive entries, so the UI can show a roadmap item without a CTA. */
export function servicesInCategory(category: CareerServiceCategory): CareerService[] {
  return CAREER_SERVICES.filter((service) => service.category === category)
}

export function getCareerService(code: string): CareerService | undefined {
  return CAREER_SERVICES.find((service) => service.code === code)
}

export function requireCareerService(code: string): CareerService {
  const service = getCareerService(code)
  if (!service) throw new Error(`Unknown career service: ${code}`)
  return service
}

export function servicesByCategory(category: CareerServiceCategory): CareerService[] {
  return ACTIVE_CAREER_SERVICES.filter((service) => service.category === category)
}
