-- Activate Terms & Conditions v1.0
-- Version: 1.0 | Effective: 13 September 2026

UPDATE privacy_policies SET
  version = '1.0',
  effective_date = '2026-09-13',
  last_updated_date = '2026-09-13',
  is_active = true,
  content_en = E'TERMS & CONDITIONS\n\nVersion 1.0 | Effective: 13 September 2026\nOperator: SUCCESS EDU HUB (SEH International Academy)\nPlatform: Talent Verify / SEH Talent & Career Network\nJurisdiction: Hashemite Kingdom of Jordan\n\n1. SERVICE DESCRIPTION\nTalent Verify is a professional talent and career development platform operated by SUCCESS EDU HUB.\n\n2. USER ROLES\nCandidates: Individuals seeking career opportunities or professional development.\nEmployers/HR: Organizations recruiting talent and managing recruitment services.\nAdmins: Platform operators and support staff.\n\n3. VERIFICATION\nTalent Verify verification is a platform certification only and does not guarantee employment or hiring outcomes.\nEmployers make independent hiring decisions based on their own criteria.\n\n4. DATA & PRIVACY\nUser data is processed per the Privacy Policy.\nCandidates control their professional profile visibility to employers.\nEmployers access only authorized, verified candidate data per product rules.\n\n5. ACCEPTABLE USE\nUsers must not: Share others\' credentials, upload malicious content, scrape data, abuse automation, or violate applicable laws.\nViolations may result in account suspension or termination.\n\n6. LIABILITY\nService provided as-is. We are not liable for employment outcomes, lost opportunities, or indirect damages.\n\n7. TERMINATION\nWe may terminate accounts for policy violations, with or without notice.\n\n8. CHANGES\nWe may update these terms. Continued use implies acceptance.\n\n9. SUPPORT & INQUIRIES\nFor questions, use the Contact Support feature within the platform or privacy settings.',
  content_ar = E'الشروط والأحكام\n\nالإصدار 1.0 | ساري المفعول: 13 سبتمبر 2026\nالمشغّل: SUCCESS EDU HUB (أكاديمية SEH الدولية)\nالمنصة: Talent Verify / شبكة SEH للمواهب والتطور الوظيفي\nالولاية القضائية: المملكة الأردنية الهاشمية\n\n1. وصف الخدمة\nTalent Verify هي منصة احترافية للمواهب والتطور الوظيفي يديرها SUCCESS EDU HUB.\n\n2. أدوار المستخدمين\nالمرشحون: الأفراد الذين يسعون إلى فرص عمل أو تطور مهني.\nأصحاب العمل / الموارس البشرية: المنظمات التي تجند المواهب.\nالمسؤولون: مشغلو المنصة وموظفو الدعم.\n\n3. التحقق\nالتحقق من Talent Verify هو شهادة منصة فقط ولا يضمن العمل أو نتائج التوظيف.\nيتخذ أصحاب العمل قرارات التوظيف بشكل مستقل.\n\n4. البيانات والخصوصية\nتتم معالجة بيانات المستخدم وفقاً لسياسة الخصوصية.\nيتحكم المرشحون برؤية ملفهم المهني.\nيصل أصحاب العمل فقط إلى بيانات المرشحين المصرح بها والمتحققة.\n\n5. الاستخدام المقبول\nيجب على المستخدمين عدم: مشاركة بيانات اعتماد الآخرين أو تحميل محتوى ضار أو كشط البيانات.\nقد تؤدي الانتهاكات إلى إيقاف الحساب أو إغلاقه.\n\n6. المسؤولية\nالخدمة كما هي. لا نتحمل مسؤولية نتائج التوظيف.\n\n7. الإنهاء\nقد نقوم بإنهاء الحسابات بسبب انتهاك السياسة.\n\n8. التغييرات\nقد نقوم بتحديث هذه الشروط.\n\n9. الدعم\nللأسئلة، استخدم ميزة الدعم داخل المنصة.'
WHERE policy_key = 'terms_of_service';
